### ISSUE TITLE
运行时报错   大神

### ISSUE THREAD

**Issue by RoshanGH** [Strikersb/webdirscan#4]
➜  webdirscan git:(master) ✗ ./webdirscan.py -t 100 www.bus999.com
Dirscan is running!
Scan target: http://www.bus999.com
Total Dictionary: 79078
[200]http://www.bus999.com/robots.txt
[200]http://www.bus999.com/login.php
[200]http://www.bus999.com/.git/config
[200]http://www.bus999.com/robots.txt
[200]http://www.bus999.com/.htaccess
[200]http://www.bus999.com/watch
Exception in thread Thread-99:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./webdirscan.py", line 73, in run
    self._scan(url)
  File "./webdirscan.py", line 59, in _scan
    html_result = requests.get(url, headers=self.headers, allow_redirects=False, timeout=60)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 658, in send
    r.content
  File "/Library/Python/2.7/site-packages/requests/models.py", line 823, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 748, in generate
    raise ChunkedEncodingError(e)
ChunkedEncodingError: ("Connection broken: error(54, 'Connection reset by peer')", error(54, 'Connection reset by peer'))

[200]http://www.bus999.com/robots.txt

**Comment by labrusca** [comment]
连接被服务器端重置了，有可能是因为服务器做了安全机制，改下headers或者线程数少点
